package com.cafe_bazaar.venue.app

object Constants {

    const val BASE_URL = "https://api.foursquare.com/v2/"
    const val CLIENT_ID = "HCP105BBHZKBKHFXPRERHIE34YGSRZWTKWKAL5LF3MXGZDFU"
    const val CLIENT_SECRET = "K0UZYKDPBKFYWAGKKGJUUXMYS2330OKNDZ45OPMVELF1MGPY"
    const val API_V_PARAM = "20120609"
    const val VENUES_LIST_LIMIT: Int = 5
    const val SP_FILE_NAME: String = "TASK_SHARED_PREF"
    const val DATABASE_NAME = "VENUE_DATABASE"

    const val PREF_KEY_LAST_LOCATION_LATITUDE = "PREF_KEY_LAST_LOCATION_LATITUDE"
    const val PREF_KEY_LAST_LOCATION_LONGITUDE = "PREF_KEY_LAST_LOCATION_LONGITUDE"
    const val PREF_KEY_LAST_API_CALL = "PREF_KEY_LAST_API_CALL"
}